Vagrant.configure("2") do |config|
  #config.vm.box = "ubuntu/bionic64"
  config.vm.box = "bento/ubuntu-18.04"
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 1024 * 2
    vb.cpus   = 2
    vb.gui    = true
    vb.customize [
      "modifyvm", :id,
      "--vram", "256",                  # ビデオメモリ確保（フルスクリーンモードにするため）
      "--clipboard", "bidirectional",   # クリップボードの共有
      "--draganddrop", "bidirectional", # ドラッグアンドドロップ可能に
      "--cpus", "2",                    # CPUは2つ
      "--ioapic", "on"                  # I/O APICを有効化
    ]
  end

  config.vm.define "suna-18" do |c|
    c.vm.hostname = "suna-18"
    c.vm.network "private_network", ip: "192.168.33.12"
  end
end
