$web_provision = <<WEB_PROVISION
echo "================[ WEB PROVISION ]"
apt-get update -qq
apt-get install -y -qq nginx mysql-client
WEB_PROVISION

$db_provision = <<DB_PROVISION
echo "================[ DB PROVISION ]"
export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
apt-get install -y -qq mysql-server
sed -i -e "s/127.0.0.1/0.0.0.0/" /etc/mysql/mariadb.conf.d/50-server.cnf
/etc/init.d/mysql restart
mysql -u root mysql <<< "GRANT ALL ON *.* TO 'root'@'%' IDENTIFIED BY 'root'; FLUSH PRIVILEGES;"
DB_PROVISION

Vagrant.configure("2") do |config|
  config.vm.box = "debian/stretch64"
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.define "web" do |web|
    web.vm.provision "shell", inline: $web_provision
    web.vm.network "forwarded_port", guest: 80, host: 8080
    web.vm.network "private_network", ip: "192.168.34.10"
  end

  config.vm.define "db" do |db|
    db.vm.network "private_network", ip: "192.168.34.11"
    db.vm.provision "shell", inline: $db_provision
  end
end
