---

# OSの違いによって挙動を変える
#- include_tasks: setup-Redhat.yml
#  when: ansible_os_family == 'RedHat'

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: localeの作成
  locale_gen:
    name: ja_JP.UTF-8
    state: present

- name: システムロケールの確認
  command: localectl status
  register: localectl_result
  check_mode: no
  changed_when: false

- name: localeのセット
  command: localectl set-locale LANG=ja_JP.utf8
  when: "'LANG=ja_JP.utf8' not in localectl_result.stdout"
