Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu1804"
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provider "virtualbox" do |vb|
    vb.gui    = false
    vb.memory = 1024 * 2
    vb.cpus   = 2
  end

  config.vm.define "suna-vm" do |c|
    c.vm.hostname = "suna"
    c.vm.network "private_network", ip: "192.168.33.11"
  end
  #config.vm.define "kan-vm" do |c|
  #  c.vm.hostname = "kan"
  #  c.vm.network "private_network", ip: "192.168.33.12"
  #end
end
