---

devs:
  hosts:
    suna:
      ansible_ssh_host: 192.168.33.11
      ansible_ssh_port: 22
      ansible_ssh_user: vagrant
      ansible_ssh_pass: vagrant
      ansible_ssh_extra_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
